# Generated by Django 3.2.24 on 2024-03-19 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0003_auto_20240315_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juegos',
            name='nombre',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
