# Generated by Django 3.2.24 on 2024-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto', '0004_alter_juegos_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consolas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('año_lanzamiento', models.EmailField(max_length=254)),
                ('Empresa', models.CharField(max_length=40)),
            ],
        ),
    ]
